<?php require 'config.php';

ini_set('display_errors', false);
ini_set('display_startup_errors', false);

if (! is_dir($config['album1584']) || ! is_writable($config['album1584'])) {
    exit(sprintf('The directory "%s" does not exist or is not writable', $config['album1584']));
}

if (! file_exists($config['flash_texts']) || ! is_writable($config['flash_texts'])) {
    exit(sprintf('The file "%s" does not exist or is not writable', $config['flash_texts']));
}

if (! is_dir('logs')) {
    mkdir('logs', 0777, true);
}

date_default_timezone_set($config['timezone']);

ob_start();
echo "/**\n";
echo " * This file is automatically generated.\n";
echo " */\n\n";
echo sprintf("[%s] Started!\n", date('d/M/Y:H:i:s'));

$context = stream_context_create([
    'http' => [
        'user_agent' => 'habbo-sucks',
    ],
    'ssl' => [
        'verify_peer'      => false,
        'verify_peer_name' => false,
    ],
]);

$counter = 0;

foreach ($config['locales'] as $locale) {
    echo "> Processing external_flash_texts ...\n";

    $file   = sprintf('https://www.habbo.%s/gamedata/external_flash_texts/1', $locale);
    $result = file_get_contents($file, false, $context);

    if ($result === false) {
        continue;
    }

    $result = file_put_contents('flash_texts.tmp', $result);

    if ($result === false) {
        continue;
    }

    $handle = fopen('flash_texts.tmp', 'r');

    if (! $handle) {
        echo "> Failed!\n";
        continue;
    }

    while ($line = fgets($handle)) {
        list($name, $value) = explode('=', $line);

        $code = str_replace(['badge_name', 'badge_desc'], '', $name);
        $code = trim($code, '_');
        $code = trim($code);

        if (strpos($name, 'badge_name') !== false) {
            $badges[$code]['name'] = $value;
        }

        if (strpos($name, 'badge_desc') !== false) {
            $badges[$code]['desc'] = $value;
        }
    }

    fclose($handle);
    $buffer = "\n";

    foreach ($badges as $code => $values) {
        $url  = sprintf('https://images.habbo.com/c_images/album1584/%s.gif', $code);
        $file = sprintf('%s/%s.gif', $config['album1584'], $code);

        if (file_exists($file)) {
            continue;
        }

        $result = file_get_contents($url, false, $context);

        if ($result === false) {
            continue;
        }

        $result = file_put_contents($file, $result);

        if ($result === false) {
            continue;
        }

        echo "> Downloaded: $url\n";

        if (isset($values['name'])) {
            $buffer .= sprintf("badge_name_%s=%s", $code, $values['name']);
        }

        if (isset($values['desc'])) {
            $buffer .= sprintf("badge_desc_%s=%s", $code, $values['desc']);
        }

        $counter++;
    }

    $result = file_put_contents($config['flash_texts'], $buffer, FILE_APPEND | LOCK_EX);

    if ($result === false) {
        continue;
    }
}

if ($counter > 0) {
    $message = "total badges added: $counter";
} else {
    $message = "your badges are up to date!";
}

echo sprintf('[%s] Finished, %s', date('d/M/Y:H:i:s'), $message . PHP_EOL);

file_put_contents('logs/update.log', ob_get_clean());
